# used only for debugging release.yml
# will be deleted after. Minimzed to increase speed.
name: Build Binaries
on:
  workflow_dispatch:
  workflow_call:
env:
  CGO_ENABLED: 1
jobs:

  build-linux-arm:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set vars
        id: vars
        run: echo "version=$(git describe --tags --match v[0-9]* 2> /dev/null)" >> $GITHUB_OUTPUT
      - name: Pull docker  image
        run: docker pull ghcr.io/zk-org/zk-xcompile:linux-arm64
      - name: Build
        run: |
          docker run --rm \
            -v $(pwd):/usr/src/zk \
            -w /usr/src/zk \
            -u root \
            ghcr.io/zk-org/zk-xcompile:linux-arm64 \
            /bin/bash -c 'go build -buildvcs=false -tags "fts5" -ldflags "-X=main.Version=${{ steps.vars.outputs.version }} -X=main.Build=${{ steps.vars.outputs.version }}"'
      - name: Compress for upload
        run: tar -cvz zk > zk-${{ steps.vars.outputs.version }}-linux-arm64.tar.gz
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zk-${{ steps.vars.outputs.version }}-linux-arm64.tar.gz
          path: zk-${{ steps.vars.outputs.version }}-linux-arm64.tar.gz

