name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-binaries:
    uses: ./.github/workflows/build-binaries.yml

  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # required for release creation
    needs: [build-binaries]
    steps:
      - name: Download artifacts from 'build binaries' workflow
        uses: actions/download-artifact@v4
        with: 
          path: zk
          pattern: zk-${{ github.ref_name }}-*
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: zk*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
